# Let's upload reprox to PyPi to make it pip installable
# Mostly based on https://github.com/marketplace/actions/pypi-publish
name: Pipy
on:
  push:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Setup steps
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install wheel
      - name: Build package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_password }}
        run:
         | 
         pip install twine 
         python setup.py sdist bdist_wheel
         twine upload dist/*.whl
